[workspace]
members = ["crates/brainfuck", "crates/harfbuzz-wasm", "crates/shaper"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
bf-fast = "0.0.5"
wasm-bindgen = "0.2.92"
